### ISSUE TITLE
xfce pol kit lets others sneak in

### ISSUE THREAD

**Issue by ToddAndMargo** [ncopa/xfce-polkit#5]
Fedora 29
Xfce 4.13

Dear Xfce-polkit,

Whenever I put the root password into xfce Pol kit, I can run other root programs for about 10 seconds after the first Pol Kit prompt without having to enter root's password again.  This give me the creeps.

For instance qemu-kvm's "virt-manager" pops a xfce pol kit prompt but flies right through if I have enter the pol kits root password somewhere else within the last 10 seconds.

Please fix.  This is pretty big security hole.

Many thanks,
-T

**Comment by ncopa** [comment]
I dont think this is something that can be fixed in xfce-polkit. It needs to be fixed in the polkit configuration or in polkit itself.

**Comment by ToddAndMargo** [comment]
Would you please move this bug to the appropriate place.  This is a security issue

**Comment by ncopa** [comment]
> Would you please move this bug to the appropriate place. This is a security issue

Sorry. I have no clue what is wrong on your system and it does not happen here.

Maybe ask someone at fedora? I don't use fedora my self.

**Comment by ncopa** [comment]
I tried to reproduce it in fedora 32 but was not able to. I installed virt-manager and started it. I got a prompt for password. After entering the password I ran `pkexec` within 10 seconds and got prompted immediately. I tried to run `pkexec ls -la /root && pkexec` and i got prompted for password twice.

Looking at the polkit documentation, there seems to be a `auth_admin_keep` option, which gives the behavior you are describing.

> Keep in mind that if polkit.Result.AUTH_SELF_KEEP or polkit.Result.AUTH_ADMIN_KEEP is returned, authorization checks for the same action identifier and subject will succeed (that is, return polkit.Result.YES) for the next brief period (e.g. five minutes) even if the variables passed along with the check are different.

https://www.freedesktop.org/software/polkit/docs/latest/polkit.8.html

So I believe you have a problem in your configuration.

In either case, this is not anything that can be fixed in xfce-polkit, nor is it my responsibility to investigate where appropriate place to report your problems are. Sorry.
